### ISSUE TITLE
The client initialization did not verify the hostname

### ISSUE THREAD

**Issue by muei** [SocketCluster/socketcluster-client#105]
```
const { connect } = require('socketcluster-client')
const socket = connect({
  // hostname: 'localhost',
  port: 3333
})
```
In node env, the instance `socket` above with init no hostname, so the hostname will be undefined, but the instance will be create sucess. I don't think this is a good way, I suggest
- Valid the `hostname` option item
-  Set default value as 'localhost'
- Throw exception

**Comment by MegaGM** [comment]
It's not the best idea to throw exception here, I believe. It'd be impossible to use `port` without `hostname` option then.

**Comment by MegaGM** [comment]
Though probably it'd be better to use either `hostname` + `port`, or `host` alone. Not together.
Check out the conversation https://github.com/SocketCluster/socketcluster-client/pull/110
