### ISSUE TITLE
undefined is not an object (evaluating 'n[l].apply')

### ISSUE THREAD

**Issue by felippepuhle** [SocketCluster/socketcluster-client#129]
I'm using `socketcluster-client` on React Native and the app crashes sometimes when phone is idle... any guess on that?

Apparently something on `component-emitter`:

<img width="1079" alt="Screen Shot 2019-07-02 at 11 46 44 AM" src="https://user-images.githubusercontent.com/15961929/60522301-18c8a500-9cbf-11e9-92b3-31ccbabc5574.png">

Thanks!

**Comment by jondubois** [comment]
@felippepuhle Maybe one of your event handlers was undefined. For example:

```
socket.on('someevent', undefined);
```

**Comment by felippepuhle** [comment]
@jondubois unfortunately I couldn't find what's causing this yet, but only happens sometimes when the phone was idle and user try to open the app again...

Probably it's not this, 'cause I don't have any untracked event... only those that usually work without being idle previously

I made some changes on my `authEngine`, don't know if will fix it yet.

Thanks!

**Comment by felippepuhle** [comment]
Found and fixed.

Apparently, a ping timeout was throwing an error and I had an undefined `onError` here:  `socket.on('error', onError)`

Thanks!
