### ISSUE TITLE
Can I set the jwtToken? 

### ISSUE THREAD

**Issue by mzupek** [SocketCluster/socketcluster-client#130]
I am using react native and just want to set the token rather than having it read from local storage? setAuthToken()? I tried passing through authToken on 'create'? can I emit it? Any help is much appreciated

**Comment by jondubois** [comment]
@mzupek From the server side you can create a new token using `socket.setAuthToken(myTokenObject)`.

`myTokenObject` should be an object; you can have any JSON property/value inside it.

If your token comes from a third-party auth service or a separate microservice, you can pass it to the client-side in any way you want and then add it to localStorage before you create the socket.

Alternatively, you can pass an `authEngine` option when you create the socket which contains a custom client-side auth engine instance - This instance must implement a `saveToken`, `removeToken` and `loadToken` method. This gives you the maximum control over where and how to save, remove and load the JWT on the client side.

**Comment by mzupek** [comment]
I am just getting the token back from a microserivce. Since I am using this in react native can I store it to the devices localStorage and will that work? my guess is not? Do you have an example of the authEngine option? thanks for your help in advance

**Comment by mzupek** [comment]
Closing

**Comment by kishor82** [comment]
@mzupek , Would have been helpful if you had commented on solutions before closing this thread.

**Comment by jondubois** [comment]
For future reference, it's possible to use a JWT token generated from a different microservice for use by SC using `localStorage.setItem('socketcluster.authToken', token);`.

See HTTP authentication flow here: https://socketcluster.io/docs/authentication/#http-flow
