### ISSUE TITLE
socketcluster-client with protocol v1

### ISSUE THREAD

**Issue by tscislo** [SocketCluster/socketcluster-client#147]
Hey!

Is there a way to use socketcluster-client v 14.x with protocol v1?

**Comment by MegaGM** [comment]
All versions of `socketcluster-server <=v14.x.x` and `socketcluster-client <=v14.x.x` use protocol v1 exclusively.  
All versions of `socketcluster-server >=v15.x.x` and `socketcluster-client >=v15.x.x` use protocol v2 by default and support compatibility mode, which allows them to work with a counterpart which uses protocol v1.

`socketcluster-client <=v14.x.x` works with `socketcluster-server >=v15.x.x`,  
when `socketcluster-server >=v15.x.x` uses `protocolVersion: 1` configuration option.  

`socketcluster-client >=v15.x.x` works with `socketcluster-server <=v14.x.x`,  
when `socketcluster-client >=v15.x.x` uses `protocolVersion: 1` configuration option.  

This remains a fact as of `socketcluster@17.2.0` and, AFAIK, there is no plans to ever change this compatibility in the future.
