### ISSUE TITLE
SyntaxError: Identifier 'global' has already been declared

### ISSUE THREAD

**Issue by johnny-mcfadden-dailypay** [SocketCluster/socketcluster-client#153]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `socketcluster-client@19.1.2` for the project I'm working on (`"expo": "51.0.17"` + `"react-native": "0.74.2"` being the main upgrade drivers that resulted in this issue). 

On web, we are running into an issue with `global` already declared, causing our web bundling to fail.  

<img width="525" alt="Screenshot 2024-07-01 at 14 28 46" src="https://github.com/SocketCluster/socketcluster-client/assets/93137292/a88a3b0b-6730-4f28-894e-1f7a16378157">

Here is the diff that solved my problem that I hoped to shared with others. 

```diff
diff --git a/node_modules/socketcluster-client/lib/ws-browser.js b/node_modules/socketcluster-client/lib/ws-browser.js
index 32e279c..1614e0d 100644
--- a/node_modules/socketcluster-client/lib/ws-browser.js
+++ b/node_modules/socketcluster-client/lib/ws-browser.js
@@ -1,11 +1,11 @@
-let global;
+let globalScope;
 if (typeof WorkerGlobalScope !== 'undefined') {
-  global = self;
+  globalScope = self;
 } else {
-  global = typeof window !== 'undefined' && window || (function() { return this; })();
+  globalScope = typeof window !== 'undefined' && window || (function() { return this; })();
 }
 
-const WebSocket = global.WebSocket || global.MozWebSocket;
+const WebSocket = globalScope.WebSocket || globalScope.MozWebSocket;
 
 /**
  * WebSocket constructor.
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jondubois** [comment]
@johnny-mcfadden-dailypay Thanks for this report. This suggestion has been implemented and published as `socketcluster-client@19.2.2`.
