### ISSUE TITLE
Unable to intercept error

### ISSUE THREAD

**Issue by KCypher13** [SocketCluster/socketcluster-client#21]
Hi,

When I send back an error from my server after an emit like this : 
```javascript
socket.on('login', function(data, res){
  if(login.status == "fail"){
    res('incorrect email');
  }
}
```

I get this kind of message in my chrome console : 
```
Uncaught incorrect email
```

Is there any way to catch the error ?

PS : I'm on SC1

**Comment by jondubois** [comment]
Did you try adding an error handler on the client ```socket.on('error', function () {});```?

**Comment by KCypher13** [comment]
Ok, it's easiest as that...

Thanks for the quick response ! :)
