### ISSUE TITLE
Add 'subscribeRequest' event to client

### ISSUE THREAD

**Issue by mattkrick** [SocketCluster/socketcluster-client#25]
Currently, the `subscribe` method internally adds the sub & its pending state to a queue, but it doesn't emit anything, so nothing else in the app knows we're trying to subscribe. This would be useful for showing a loading UI on recently mounted components.

I propose emitting a `subscribeRequest` event at the bottom of `SCSocket.prototype.subscribe`. Will be happy to submit a PR & update docs.

**Comment by jondubois** [comment]
@mattkrick Yes that sounds like a good addition. PR welcome.
