### ISSUE TITLE
Reuse connection instance

### ISSUE THREAD

**Issue by mattkrick** [SocketCluster/socketcluster-client#27]
Each call to `connect()` creates a new connection. If I call this from different components, I'll end up with a bunch of different connections, each with their own subs. Socket.io handles this with a manager & allows for multiplexing.

In socket.io:
```
s1 = socketIO.connect();
s2 = socketIO.connect();
s1 === s2 //true
```

Would is be possible to do the same with SC?

**Comment by jondubois** [comment]
Right now you have to make sure you pass around the same socket object to all components which want to share it.

I think we could implement multiplexing functionality like Socket.io. I think we also should have an option to set multiplex to false just like in Socket.io. A pull request would be welcome.
