### ISSUE TITLE
v3.1.0 breaks in react-native

### ISSUE THREAD

**Issue by sjmueller** [SocketCluster/socketcluster-client#35]
Some recent changes have broken compatibility with react-native.  When running socketcluster-client within iOS JavascriptCore environment, the following exception occurs:

`Can't find variable: location`

I suspect it has to do with something in scsocketcreator:

https://github.com/SocketCluster/socketcluster-client/blob/ccba9f743274ec94665ce9ff591fa1738818c493/lib/scsocketcreator.js#L13-L50

I have to dig deeper, but perhaps some of the location variable checks aren't full proof, and this variable is probably not present with JSC.

**Comment by jondubois** [comment]
Thanks for reporting. Some of the symbols within some conditional expressions where moved around (and brackets were removed) and so the logic related to default ports was actually incorrect and led to this error. This should now be fixed (v3.1.1).

**Comment by sjmueller** [comment]
Confimed that v3.1.1 works again.  Thanks for such a quick fix @jondubois!
