### ISSUE TITLE
a few requests/suggestions

### ISSUE THREAD

**Issue by r3wt** [SocketCluster/socketcluster-client#37]
- `uglifyjs --compress --mangle --screw-ie8 socketcluster.js -o ./socketcluster.min.js`
- authentication make possible to dispatch a request to an api endpoint to authenticate. this make it easy to integrate with a website, for instance an app using php or python that can really benefit by sticking to what it is good at, and letting the socket cluster generate the real time data feeds.
- documentation

**Comment by jondubois** [comment]
- If someone wants to add this as an additional build process to package.json then that's sounds fine.
- HTTP authentication is outside the immediate scope of SC but using JWT generated from an external service is definitely supported.
- Hopefully documentation has improved since then.
