### ISSUE TITLE
How do I handle a connection error?

### ISSUE THREAD

**Issue by seiyria** [SocketCluster/socketcluster-client#38]
I'm not sure if I'm supposed to try/catch (since the socket repeatedly tries to connect), watch for an event, or what. I've read [this](http://socketcluster.io/#!/docs/handling-failure) but it only covers errors that I publish. I'm trying to watch for a "socket hung up" which appears to be thrown when the client can't connect to the server, so I can pop up a message in my application saying that the server isn't reachable.

**Comment by jondubois** [comment]
@seiyria ```socket.on('error', function (err) {...})``` to handle errors on the client socket.

**Comment by seiyria** [comment]
Awesome, thank you! Is there somewhere in the documentation that lists built-in events?
