### ISSUE TITLE
JavaScript file does not get served

### ISSUE THREAD

**Issue by eickeee** [SocketCluster/socketcluster-client#43]
Hey,
I think I've might encountered a problem in the client. 
You state in the description that the js file should usually be served automatically.
However, even in your [sample](https://github.com/SocketCluster/socketcluster/tree/master/sample) it is not available for me. (**npm install** and **node server.js** were executed before)

<img width="1436" alt="screen shot 2016-02-24 at 22 33 51" src="https://cloud.githubusercontent.com/assets/5420972/13301762/cdc10cf6-db46-11e5-8868-c9051aad1616.png">

**Comment by jondubois** [comment]
@eickeee It should work if you created your app using the ```socketcluster create myapp``` command.
Otherwise, you will need to copy the file ```socketcluster-client/socketcluster.js``` to your ```public/``` directory (```public/socketcluster.js```).

**Comment by eickeee** [comment]
Well, if I create an app using the command, it puts the needed js file automatically in the public folder.
However, since you offer the client on npm, I assumed that you do some magic like e.g. socket.io does (they serve the file under /socket.io/socket.io.js) and make the file available although the file is not explicitly lying in the public folder. 
I thought that this was the intended behaviour, that's why I was asking. But if it's not the case, I'll put the js file in the public folder manually.

**Comment by deoqc** [comment]
Wondering how to do this in React Native. Have to put the file manually in a directory also? 

I am having the following error:

Unable to resolve module querystring from .../app/node_modules/socketcluster-client/lib/scsocket.js:

**Comment by jondubois** [comment]
Hopefully this is no longer an issue.
