### ISSUE TITLE
`global.WebSocket` throws in some eviroments

### ISSUE THREAD

**Issue by zalmoxisus** [SocketCluster/socketcluster-client#45]
As you see from https://github.com/zalmoxisus/remote-redux-devtools/issues/6, sometimes either babel or react-native packager adds `'use strict';` to the dependencies, and this [makes `global` to be `undefined`](https://github.com/webpack/webpack-dev-server/issues/174#issuecomment-102303060).

Maybe in `browser.js` instead of `var WebSocket = global.WebSocket || global.MozWebSocket`, we could use `var WebSocket = this.WebSocket || global.WebSocket || global.MozWebSocket` as @mlabrum suggested?

**Comment by jondubois** [comment]
@zalmoxisus Does this affect the latest version of socketcluster-client?
I remember fixing something like this a while ago: https://github.com/SocketCluster/socketcluster-client/issues/40

The issues was in the ws module - In response to this, we rolled back to using our own fork (sc-ws) of the ws module. See https://github.com/SocketCluster/socketcluster-client/commit/c9cb35172b493159611346f4165ad3a582d21c45

I thought that fixed the issue?

**Comment by zalmoxisus** [comment]
Yes, we use the latest version. The error comes from `sc-ws/lib/browser`:
```js
/**
 * Module dependencies.
 */

var global = (function() { return this; })();

/**
 * WebSocket constructor.
 */

var WebSocket = global.WebSocket || global.MozWebSocket;
```

So, `'use strict';` makes `var global = (function() { return this; })();` to be `undefined` and in the next line we a trying to read the property of  `undefined`.

**Comment by zalmoxisus** [comment]
I'd suggest to replace that line with:
```js
var WebSocket = window && window.WebSocket || global.WebSocket || global.MozWebSocket;
```

**Comment by jondubois** [comment]
@zalmoxisus Ok this should be fixed in socketcluster-client v4.3.10 - Make sure it also updates to the latest sc-ws module v1.0.2 https://www.npmjs.com/package/sc-ws

**Comment by zalmoxisus** [comment]
@jondubois, thanks a lot for the quick fix! Tested, it solves the problem with Babel. Don't have the possibility to check with React Native now, but, looking through the sources, it should expose window object.

**Comment by zalmoxisus** [comment]
It seems there are [more issues](https://github.com/zalmoxisus/remote-redux-devtools/issues/6#issuecomment-200412614) in other modules to get `socketcluster-client` work in strict mode. With https://github.com/facebook/react-native/pull/5796 now React Native adds strict mode by default.

**Comment by zalmoxisus** [comment]
Looking into it, the strict mode doesn't allow `arguments.callee` used in `sc-errors`([Why was arguments.callee removed from ES5 strict mode?](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee).

But it should be another problem that calls the error function. I'll try to investigate it later and come with a solution.

**Comment by jondubois** [comment]
@zalmoxisus Ok this should be fixed, you need to make sure to update the ```sc-errors``` dependency.

I'm not sure why it's throwing the TimeoutError... This can happen if you did a ```socket.emit('myEvent', data, callback);``` on the client (expecting a callback) and then on the server you forget to invoke the respond function ```socket.on('myEvent', function (data, respond) { ... You need to invoke the respond() method here or else the client-side callback will timeout ...})```.

**Comment by zalmoxisus** [comment]
@jondubois, thanks for the fix and for the detailed explanation! Actually, I cannot reproduce that error in a non React Native environment. The client [has a callback](https://github.com/zalmoxisus/remote-redux-devtools/blob/master/src/devTools.js#L67) and [the server responds to it](https://github.com/zalmoxisus/remotedev-server/blob/master/bin/worker.js#L38). Will investigate further.

**Comment by zalmoxisus** [comment]
[It works](https://github.com/zalmoxisus/remote-redux-devtools/issues/6#issuecomment-200871929). Thanks a lot, @jondubois!
