### ISSUE TITLE
EXCEPTION: SocketProtocolError: Socket hung up

### ISSUE THREAD

**Issue by ansarizafar** [SocketCluster/socketcluster-client#50]
I am getting this error in firefox and in chrome for android. Please help.

**Comment by DarkMukke** [comment]
in your worker.js add 

        scServer.on('closure', (socket) => {
        });
        scServer.on('disconnection', (socket) => {
        });

to suppress the message

**Comment by jondubois** [comment]
This is a generic error which means that the client could not reach the server; there could be many reasons for this; bad internet connection, proxies, incorrect parameters passed when creating the client socket, etc...
