### ISSUE TITLE
Add an event to check when the auth token is updated on the client

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster-client#52]
There is no event to check when the auth token is updated on the client if the socket is already authenticated.

**Comment by mauritslamers** [comment]
I think it goes further. It doesn't seem like the information in the authToken is actually updated when it changes on the server. As it is a kind of shared session object, certain settings on the session are very useful on the client side, and having an updated version of that information saves a call to the server.

**Comment by jondubois** [comment]
@mauritslamers Yes, there was a bug there. Thanks for reporting. It has now been fixed in v4.3.19. Also a new ```authTokenChange``` event was added so you can listen to token updates even if socket is already authenticated. I updated the website too http://socketcluster.io/#!/docs/api-scsocket-client
