### ISSUE TITLE
RN: Could not invoke WebSocketModule.connect

### ISSUE THREAD

**Issue by pewh** [SocketCluster/socketcluster-client#55]
It didn't work on React Native.

![1](https://cloud.githubusercontent.com/assets/881358/17090579/0313e0c2-525c-11e6-81dd-d5f3f76e66cf.png)
Tested on RN 0.29.2.

**Comment by jondubois** [comment]
@pewh Strange. None of these lines refer to SocketCluster code. Could this be an issue with RN itself?

It looks very similar to this issue:
https://github.com/facebook/react-native/issues/5969

**Comment by pewh** [comment]
Yes. It seems an issue by RN itself. I reproduce that error by create new RN starter & add `const ws = new WebSocket('ws://anything-host')`.

I'm not sure if it's related with facebook/react-native#5969, but I'll close this.

**Comment by jondubois** [comment]
@pewh Feel free to post here if you find a solution to this problem.
