### ISSUE TITLE
Socketcluster Client Library :

### ISSUE THREAD

**Issue by sacOO7** [SocketCluster/socketcluster-client#59]
I want to develop native android client library for socketcluster .Current available libraries are based on Webview jsbridge which degrades performance of connection. Can you provide me with some sort of documentation so that I can contribute to development of java client library for socketcluster.

**Comment by jondubois** [comment]
SC's protocol has not yet been formally documented. I would love to write it up when I have the time, but I'm extremely busy with other stuff at the moment.

The best approach at the moment is to use the official JavaScript client and try it out in your Chrome browser - If you open the developer panel and click on `Network` tab and select the WebSocket connection, you will be able to see all the raw WebSocket messages - That way you can see what the messages look like when SC does the handshake, authentication and to perform various actions.

If you have any specific questions you can ask them here https://gitter.im/SocketCluster/socketcluster and tag me using @jondubois or you can message me directly on Gitter - I try to answer as quickly as possible.

If you do go down that path and write a native Android client, it would be awesome if you could also write up documentation for the protocol as well (as you learn) - That would help other developers write more clients in the future. Some devs have asked for a C/C++ client for example but without formal docs of the protocol, they tend to get discouraged. I would be happy to help as much as possible and answer any of your questions directly.

I know abpopov was working (or considering working) on a native Android client at some point but I'm not sure where it's at. See https://github.com/SocketCluster/socketcluster/issues/150

**Comment by sacOO7** [comment]
Hi @jondubois I got your reply ,It was pretty helpful . I would like to write client library for android as well as well formatted documentation.Still I want your help for initial phase of development. Can you provide me with some references if possible?
