### ISSUE TITLE
socket.deauthenticate([callback]); callback don't work properly

### ISSUE THREAD

**Issue by willypuzzle** [SocketCluster/socketcluster-client#63]
I need to deauthenticate the socket before to use it but even when callback is called, sometimes, the socket is not deauthenticated.

for example:

```
socket.deauthenticate((err) => {
     if (!err){
         console.log(socket.getAuthToken()); //it returns a object instead of null
     }
})
```

**Comment by jondubois** [comment]
@willypuzzle The callback is called just before the token is removed from the client (but the socket is already deauthenticated from the server-side). If you add a setTimeout(fn, 0); the token on the client will be gone.

I guess we should change it to trigger AFTER the token was removed - That would be less confusing.

**Comment by jondubois** [comment]
@willypuzzle I updated it in socketcluster-client `v5.0.10`
