### ISSUE TITLE
v5.0.17 'socket hangup' error for React Native iOS Only, works for Browser and Andriod

### ISSUE THREAD

**Issue by bikashsharmabks** [SocketCluster/socketcluster-client#68]
Facing issue with v5.0.17 with socket hang up error for React Native iOS app only, whereas it works perfectly fine with Browser and React Native Android app.

Here is error log from Browser:
![screen shot 2016-11-03 at 4 47 23 pm](https://cloud.githubusercontent.com/assets/4053186/19964056/8314261e-a1e5-11e6-8fca-c886b704b92d.png)

Note: plist already has 
```<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

**Comment by jondubois** [comment]
@bikashsharmabks What options do you pass to `socketCluster.connect(...)`? Did does it work with `v5.0.14`?

**Comment by jondubois** [comment]
@bikashsharmabks Also, what version of `socketcluster` and `socketcluster-server` are you using on the server side?

**Comment by bikashsharmabks** [comment]
@jondubois 

Version Details:
socketcluster": 5.0.18

Here is the code which I have
```
var options = {
      hostname: 'dev.sandbox.com',
      path: '/mySocketEventCluster',
      port: 80,
    }
    this.socket = socketCluster.connect(options);

    this.socket.on('connect', function (err) {
        console.log('CONNECTED');
        //Alert.alert('hi','connected');
    });

    this.socket.on('error', function (err) {
        console.log(err);
        //Alert.alert('err', err.message);
    });
```

Note this works in browser, RN Android but not in RN iOS

**Comment by jondubois** [comment]
@bikashsharmabks Maybe try to setup a very simple thing with only basic SC logic to connect and emit events and let me know if it works . We need to rule out the possibility that this is caused by some other code, or special middleware on the backend, etc... Yesterday I did a very simple test with socketcluster-client v5.0.17 and it was connecting and publishing and receiving messages with socketcluster v5.0.18 on the server side - It was running on iOS simulator on Mac.

**Comment by bikashsharmabks** [comment]
@jondubois I worked I took a sample code socketcluster getting started and it worked for RN iOS!!!

But still wondering what is issue with my configuration as it works with Android and browser and not with iOS

**Comment by bikashsharmabks** [comment]
@jondubois I got the issue I was setting wsEngine to 'ws' which is not workging for iOS and when I change it to 'uws' it worked!!!

so is there any issue with 'ws'?

**Comment by jondubois** [comment]
Interesting, on RN iOS on the client side, it will use the native WebSocket object provided by RN which in theory *should* be compatible with both ws and uws on the server, but maybe this is not the case, I'll have to check.

**Comment by bikashsharmabks** [comment]
@jondubois thanks a lot for your help.

Please go ahead and close this issue or otherwise if you want to track the wsengine issue with this one

**Comment by yogi9999999** [comment]
@bikashsharmabks  it would be really help full if you tell me how you configured the socket cluster client in react native android.

**Comment by NomadGraphix** [comment]
This does not work in react-native iOS for HTTPS 443 server. Trying secure ws connections hasn't worked for me, but it works using localhost. Please advise.

**Comment by jondubois** [comment]
@NomadGraphix There is no `protocol` option, there is a `secure` (boolean) option though. See the list of supported options here: http://socketcluster.io/#!/docs/api-socketcluster-client

**Comment by NomadGraphix** [comment]
@jondubois Well, that is quite interesting. 👍 

@yogi9999999, @bikashsharmabks The documentation looks to be lacking on github: https://github.com/SocketCluster/socketcluster-client

This is what I was using, but it is out of date.
```javascript
var options = {
    protocol: 'https',
    hostname: 'example.com',
    port: 443
};

// Initiate the connection to the server
var socket = socketCluster.connect(options);
```
