### ISSUE TITLE
bower package

### ISSUE THREAD

**Issue by seiyria** [SocketCluster/socketcluster-client#7]
It'd be nice to have this on bower so those of us that don't use browserify could still install this.

**Comment by jondubois** [comment]
Note that you do not necessarily need browserify to install/use it. The latest standalone build is in https://github.com/TopCloud/socketcluster-client/blob/master/socketcluster.js
Or minified:
https://github.com/TopCloud/socketcluster-client/blob/master/socketcluster.min.js

^ You do need to wrap it in your own AMD define() block if you're using RequireJS though which is a bit tedious.

I will look into putting it on bower anyway to make the install process as convenient as possible.

**Comment by seiyria** [comment]
Sure, of course. I just mean, it's much, much easier to `bower install socketcluster-client`. Basic configuration is [pretty easy](http://devhike.blogspot.com/2013/06/how-to-register-your-library-or.html).

Thanks a ton!

**Comment by hedgepigdaniel** [comment]
I'd also appreciate this - we use bower for client side package management where possible because it's flat dependency structure prevents us from having multiple versions of the same libraries and thereby making our JavaScript bundles unnecessarily big.

**Comment by jondubois** [comment]
Done
