### ISSUE TITLE
Throw an error if user tries to specify protocol: 'https' or similar

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster-client#74]
You're supposed to use `secure: true` for SSL/TLS. A lot of people use `protocol: 'https'` which is wrong.
This is a common issue which people encounter so maybe we should throw an error if they try to do this?

**Comment by MegaGM** [comment]
Not a error but warning?

**Comment by jondubois** [comment]
I think you fixed this @MegaGM :)

**Comment by MegaGM** [comment]
Well, I don't remember, thus I haven't fixed it.
