### ISSUE TITLE
Server failed to sign auth token...all off a sudden.

### ISSUE THREAD

**Issue by NomadGraphix** [SocketCluster/socketcluster-client#75]
I've been working on a project recently and have had my session-connection login completed, but for some reason in the past couple days my client has begun to send "Server failed to sign auth token." error. I've searched high and low for documentation on this error, but am coming up empty. What is my ws configuration missing?

**Comment by jondubois** [comment]
@NomadGraphix There was an short-lived issue with signing JWTs at one point a while ago when we upgraded the jsonwebtoken module but it has been resolved since. You may want to upgrade your SC version.
