### ISSUE TITLE
Avoid usage of `eval`

### ISSUE THREAD

**Issue by zalmoxisus** [SocketCluster/socketcluster-client#79]
Hey @jondubois.

Our firefox extension was rejected from AMO because we're having unsecure `eval` in the code coming from [`cycle`](https://github.com/dscape/cycle/blob/master/cycle.js#L146), which is a dependency of `sc-errors`. Is it possible to remove it? I'd suggest to use [`jsan`](https://github.com/kolodny/jsan) which is inspired by `cycle`, but doesn't have those issues, is way more performant and takes care of lots of edge cases.

**Comment by jondubois** [comment]
@zalmoxisus I'm happy to replace cycle with something else. Does `jsan` expose a `decycle` function? The `sc-errors` module doesn't actually stringify the error object into a string, it merely removes cyclic dependencies from it so that needs to be taken into account.

**Comment by zalmoxisus** [comment]
@jondubois [yes](https://github.com/kolodny/jsan/issues/7), it would be `jsan.parse(jsan.stringify(obj, null, null, {circular: '[CIRCULAR]'}))`, but probably there'd be a lighter lib for this only case.

**Comment by zalmoxisus** [comment]
@jondubois I guess we could just move here [those few lines of code](https://github.com/dscape/cycle/blob/master/cycle.js#L24-L102) with the comment indicating the source (though though that lib is also a fork). As I understand there's no need for that other function using `eval`.

**Comment by jondubois** [comment]
@zalmoxisus That sounds like a good idea especially since `sc-errors` appears to be the only place where the `cycle` module is used and yes we don't use the `retrocycle` function. So yeah we can copy that function into a file directly in sc-errors and remove the dependency to `cycle`.

**Comment by jondubois** [comment]
I can do it this week sometime, but feel free to make a PR if you have the time.

**Comment by zalmoxisus** [comment]
No probs (https://github.com/SocketCluster/sc-errors/pull/2). Just not sure if the link to the source would be sufficient for [Public Domain license](https://github.com/SocketCluster/sc-errors/pull/2).

**Comment by jondubois** [comment]
@zalmoxisus Are they referring to this license: https://en.wikipedia.org/wiki/Public-domain_software ?
If so, it appears to be very permissive "Software in the public domain can be modified, distributed, or sold even without any attribution by anyone".

**Comment by jondubois** [comment]
Your PR looks good at first glance. Thanks! I'll test and merge it this weekend if all is well.
