### ISSUE TITLE
react-native ws-browser unable to resolve error

### ISSUE THREAD

**Issue by SaurabhKshirsagar** [SocketCluster/socketcluster-client#80]
![capture](https://cloud.githubusercontent.com/assets/22885250/26406525/24eef440-40b6-11e7-83d3-064d1a1b260c.PNG)

**Comment by jondubois** [comment]
@SaurabhKshirsagar Are you using he latest versions of react-native and socketcluster-client.? There were a few issues with RN but those were resolved in socketcluster-client a while ago but this might depend on the RN version as well. See https://github.com/SocketCluster/socketcluster-client/issues/67#issuecomment-303824093

**Comment by SaurabhKshirsagar** [comment]
@jondubois
i am using react-native 0.41.2 and socketcluster-client 5.3.1

**Comment by NomadGraphix** [comment]
@SaurabhKshirsagar, I just set this up in RN@42.3 and it works perfectly.

**Comment by jondubois** [comment]
@SaurabhKshirsagar Maybe check that you are passing the right options to the `socketCluster.connect` function on the front end - There was an issue with the GitHub README documentation which showed a `protocol` option - There is actually no `protocol` option; to use a secure HTTPS/WSS connection, you need to set an option `secure: true`. @NomadGraphix fixed the documentation issue here: https://github.com/SocketCluster/socketcluster-client/pull/81/files
