### ISSUE TITLE
Socket hung up error on react native android 

### ISSUE THREAD

**Issue by cogmeta** [SocketCluster/socketcluster-client#82]
I know this has been posted multiple times and it is always some simple configuration mistake or version mismatch but no matter what we try, we cant seem to get rid of this error "SocketProtocolError", message: "Socket hung up". The server and client works fine with web browsers Chrome and Firefox but not with react native. Can someone help?  Thanks in advance.

socketcluster-server@5.14.0
socketcluster-client@5.5.1

import socketCluster from 'socketcluster-client';
const socketOptions = {
    hostname: 'xxx.xxxx.xxx',
    secure : true,
    port: 443
};

 this.chatsocket = socketCluster.connect(socketOptions);
 this.chatsocket.on('connect', this.onSocketConnect.bind(this));
 this.chatsocket.on('proxyReply', this.onSocketMessage.bind(this));
 this.chatsocket.on('error', this.onSocketError.bind(this));

SocketProtocolError {name: "SocketProtocolError", message: "Socket hung up", code: 1006, stack: "SocketProtocolError: Socket hung up↵    at SCSocke…m=android&dev=true&hot=true&minify=false:8669:42)"}

**Comment by cogmeta** [comment]
![socketerror](https://user-images.githubusercontent.com/10062479/27251758-8d248ef4-536b-11e7-9f49-a97690bb2585.png)

**Comment by jondubois** [comment]
@cogmeta Did you manage to find the solution?

**Comment by cogmeta** [comment]
@jondubois Yes, Thank you. There were lots of things to fix (protocol option in socketOption, uws engine on server side, nginx settings). I will write a checklist that might benefit others as well.

**Comment by Louies89** [comment]
Hi @cogmeta 
I am trying to connect to socketcluster server using react native. I am using below scWorker code to connect:
class Worker extends SCWorker {
run() {
var httpServer = this.httpServer;
var scServer = this.scServer;
scServer.on('connection', function (socket) {
console.log('client :'+ socket.id + ' connected.');
})
}
}

And from client side
var Newsocket = socketCluster.connect({
hostname: 'localhost',
port: 80})

But it throws following error

Can anyone help me out please? And is it, I have to connect to the server using http first then i have to fire
var Newsocket = socketCluster.connect({
hostname: 'localhost',
port: 80})
from client side?

**Comment by sacOO7** [comment]
Use secure: true during making connection with server.
