### ISSUE TITLE
README does not specify autoReconnect in Connection Options

### ISSUE THREAD

**Issue by ekamgit** [SocketCluster/socketcluster-client#97]
The connection options section of the README mentions `autoReconnectOptions` but it does not set `autoReconnect: true`.

Is setting `autoReconnect: true` required if the `autoReconnectOptions` is defined? I think it is as I have been having issues maintaining a continuous connection and only just realised this option was not set in the example.

I included it now so will see how it goes.

**Comment by jondubois** [comment]
@ekamgit `autoReconnect: true` is the default so you don't have to specify it.
