### ISSUE TITLE
autoConnect and autoReconnect do not work

### ISSUE THREAD

**Issue by skarahoda** [SocketCluster/socketcluster-client#98]
Hi,

When my server is down, my client programs rise socket hang up exception and then they terminate. I looked into codes a bit. Websocket client gives connection refused error. Then socketcluster create a socket hang up excpetion. I think it should start reconnection mechanism when websocket give connection refused error.

Thanks,

Here is my sample code:

```
var socketCluster = require('socketcluster-client');
var options = {
	hostname: 'localhost',
	port: '8000',
	autoConnect: true,
	autoReconnect: true
};


var socket = socketCluster.connect(options);


socket.on('connect', onConnect);

function onConnect() {
	console.log('connected');
}


socket.on('disconnection', onDisconnect);

function onDisconnect(){
	console.log('disconnected');
}
```

**Comment by DarkMukke** [comment]
I think the auto reconnect only works after a first successful connection.
Otherwise it would spam connection refused errors.

**Comment by jondubois** [comment]
@skarahoda @DarkMukke It should still try to reconnect; even if the first connection attempt failed. The socketcluster-client uses an exponential backoff algorithm to make sure that clients don't spam the server while all trying to reconnect at once.

This means that every time a connect attempt fails, it will wait longer before it tries to reconnect again (up to a specific maximum timeout period)... But it should never stop retrying.

The values are entirely configurable in the client so you can make it retry faster, sooner and with a smaller maximum backoff interval if necessary. See `autoReconnectOptions` here https://socketcluster.io/#!/docs/api-socketcluster-client

**Comment by skarahoda** [comment]
@DarkMukke @jondubois I tried two cases:

1) open client when server is down
2) open client when server is up, when client is connected, close the server.

For both cases I expected the client tries to connect server repeatedly, However the socketcluster-client module throw an expection:

> /root/socketCluster/client/node_modules/socketcluster-client/lib/scsocket.js:532
      throw err;
      ^
SocketProtocolError: Socket hung up
    at SCSocket._onSCClose (/root/socketCluster/client/node_modules/socketcluster-client/lib/scsocket.js:629:15)
    at SCTransport.<anonymous> (/root/socketCluster/client/node_modules/socketcluster-client/lib/scsocket.js:280:12)
    at SCTransport.Emitter.emit (/root/socketCluster/client/node_modules/component-emitter/index.js:133:20)
    at SCTransport._onClose (/root/socketCluster/client/node_modules/socketcluster-client/lib/sctransport.js:203:28)
    at WebSocket.wsSocket.onclose (/root/socketCluster/client/node_modules/socketcluster-client/lib/sctransport.js:101:10)
    at WebSocket.onClose (/root/socketCluster/client/node_modules/ws/lib/EventTarget.js:103:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
    at WebSocket.emitClose (/root/socketCluster/client/node_modules/ws/lib/WebSocket.js:224:10)
    at _receiver.cleanup (/root/socketCluster/client/node_modules/ws/lib/WebSocket.js:210:41)

I debug the module and I realized the websocket module in socketcluster fires disconnection event. When the event is fired, socketcluster module throws an exception. 

Maybe I am wrong. Please try my simple example client code. I'm sure you will find the problem quickly.

Here is also server code:

`
var http = require('http');
var socketClusterServer = require('socketcluster-server');
var httpServer = http.createServer();

// Attach socketcluster-server to our httpServer
var scServer = socketClusterServer.attach(httpServer);

scServer.on('connection', onConnect);

function onConnect(socket){
    function onDisconnect(cb){
        console.error('Device Disconnected with socket id : ' + socket.id);
    }
    console.log('Device connected with socket id : ' + socket.id);
    socket.on('disconnect', onDisconnect);
}

httpServer.listen(8000);
console.log("STARTED");
`
